---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  M900:
    style: row
    columns: 4
#layout:
  MM:
    style: row
    columns: 4
